param(
)

$ErrorActionPreference = 'Stop'

$repoRoot = 'c:/Users/KAKARLA RAJESH/Downloads/PLANBUDDY_FULL_APP'
$evidenceDir = Join-Path $repoRoot 'evidence'
$secDir = Join-Path $evidenceDir 'payment'
if (!(Test-Path $secDir)) { New-Item -ItemType Directory -Path $secDir | Out-Null }

$logPath = Join-Path $secDir 'payment-step1-repo-search.log.txt'
$outPath = Join-Path $secDir 'payment-write-inventory.md'

$start = Get-Date

# Required patterns (simple substring / lightweight regex)
$patterns = @(
  @{ Category = 'payments.status';            Match = 'payments.status' },
  @{ Category = 'payment_status';            Match = 'payment_status' },
  @{ Category = 'bookings.status';          Match = 'bookings.status' },
  @{ Category = 'UPDATE payments';          Match = 'UPDATE payments' },
  @{ Category = 'UPDATE bookings';          Match = 'UPDATE bookings' },
  @{ Category = 'UPDATE refunds';           Match = 'UPDATE refunds' },
  @{ Category = 'razorpay_payment_id';     Match = 'razorpay_payment_id' },
  @{ Category = 'razorpay_order_id';       Match = 'razorpay_order_id' },
  @{ Category = 'provider_event_id';     Match = 'provider_event_id' },
  @{ Category = 'webhook_events';         Match = 'webhook_events' },
  @{ Category = 'FOR UPDATE';            Match = 'FOR UPDATE' },
  @{ Category = 'INSERT INTO refunds';   Match = 'INSERT INTO refunds' },
  @{ Category = 'ON CONFLICT';          Match = 'ON CONFLICT' },
  @{ Category = 'refunds.status';        Match = 'refunds.status' }
)

# Hard exclude directories
$excludeDirs = @(
  'node_modules','node_modules','\.git','\.next','dist','build','coverage','docs','__tests__','__test__','tests','test','tmp','temp','logs','vendor','public','assets','\.cache'
)

function Is-ExcludedPath([string]$p) {
  foreach ($d in $excludeDirs) {
    if ($p -match "\\$d\\") { return $true }
    if ($d -like '\\*') { continue }
  }
  return $false
}

# Enumerate ONLY BACKEND/planbuddy_v9 production files
$scanRoot = Join-Path $repoRoot 'BACKEND/planbuddy_v9'

# Collect candidate file list without recursion into excluded dirs
# We'll use Get-ChildItem with -Recurse but pre-filter by FullName using exclude dirs.
$extensions = @('*.js','*.ts','*.sql','*.mjs','*.cjs')

$allFiles = Get-ChildItem -Path $scanRoot -Recurse -File -Force -ErrorAction SilentlyContinue |
  Where-Object {
    $extOk = $extensions | ForEach-Object { if ($_.CompareTo($_) -eq 0) { } } # no-op
    ($extensions -contains $_.Name.Split('.')[-1]) # unused
    $true
  }

# Instead: filter by extension explicitly
$files = Get-ChildItem -Path $scanRoot -Recurse -File -Force -ErrorAction SilentlyContinue |
  Where-Object {
    $name = $_.Name
    $extOk = ($name -like '*.js') -or ($name -like '*.ts') -or ($name -like '*.sql') -or ($name -like '*.mjs') -or ($name -like '*.cjs')
    if (-not $extOk) { return $false }
    # exclude dirs by path fragments
    $p = $_.FullName
    if ($p -match '\\node_modules\\') { return $false }
    if ($p -match '\\\.git\\') { return $false }
    if ($p -match '\\\.next\\') { return $false }
    if ($p -match '\\dist\\') { return $false }
    if ($p -match '\\build\\') { return $false }
    if ($p -match '\\coverage\\') { return $false }
    if ($p -match '\\docs\\') { return $false }
    if ($p -match '\\__tests__\\') { return $false }
    if ($p -match '\\tests\\') { return $false }
    if ($p -match '\\test\\') { return $false }
    if ($p -match '\\tmp\\') { return $false }
    if ($p -match '\\temp\\') { return $false }
    if ($p -match '\\logs\\') { return $false }
    if ($p -match '\\vendor\\') { return $false }
    if ($p -match '\\public\\') { return $false }
    if ($p -match '\\assets\\') { return $false }
    if ($p -match '\\.cache\\') { return $false }
    if ($p -match '\\__tests__\\' -or $p -match '\\__test__\\') { return $false }
    return $true
  }

$productionCount = $files.Count

# Prepare output file incrementally
'---' | Out-Null
if (Test-Path $outPath) { Remove-Item $outPath -Force }

$header = @(
  '# payment-write-inventory.md',
  'Generated by scripts/security/01-search-payment-writes.ps1',
  '',
  '| File path | Line | Matched text | Category |',
  '|---|---:|---|---|'
)

Add-Content -Path $outPath -Value $header

# Also ensure log shows progress
"[STEP1] Enumerated production files under BACKEND/planbuddy_v9: $productionCount" | Tee-Object -FilePath $logPath -Append

$processed = 0
$filesWithMatches = 0
$totalMatches = 0

function EscapeMd([string]$s) {
  if ($null -eq $s) { return '' }
  # trim and collapse whitespace
  $t = ($s -replace "`r","" -replace "`n","" )
  $t = $t.Trim()
  if ($t.Length -gt 180) { $t = $t.Substring(0,180) + '…' }
  $t = $t -replace '\|','\\|'
  return $t
}

foreach ($f in $files) {
  $processed++
  if ($processed % 100 -eq 0) {
    "[STEP1] Processed $processed / $productionCount" | Tee-Object -FilePath $logPath -Append
  }

  $hasFileMatch = $false
  $lineNumber = 0

  try {
    # Stream line-by-line
    Get-Content -Path $f.FullName -Encoding UTF8 -ReadCount 1 | ForEach-Object {
      $line = $_
      $lineNumber++
      if ([string]::IsNullOrWhiteSpace($line)) { return }

      foreach ($p in $patterns) {
        # simple match where possible
        $cat = $p.Category
        $needle = $p.Match

        # substring match
        if ($line -like "*$needle*") {
          $hasFileMatch = $true
          $totalMatches++

          $row = "| $($f.FullName.Replace($repoRoot,'')).TrimStart('/\\') | $lineNumber | $(EscapeMd $line) | $cat |"
          Add-Content -Path $outPath -Value $row
          # flush by virtue of Add-Content
        }
      }
    }
  } catch {
    "[STEP1] WARN: Failed reading $($f.FullName): $($_.Exception.Message)" | Tee-Object -FilePath $logPath -Append
    continue
  }

  if ($hasFileMatch) { $filesWithMatches++ }
}

$end = Get-Date
$elapsed = New-TimeSpan -Start $start -End $end
$outSize = 0
try { $outSize = (Get-Item $outPath).Length } catch { }

"[STEP1] Completed." | Tee-Object -FilePath $logPath -Append
"[STEP1] Production files scanned: $productionCount" | Tee-Object -FilePath $logPath -Append
"[STEP1] Files containing matches: $filesWithMatches" | Tee-Object -FilePath $logPath -Append
"[STEP1] Total matches: $totalMatches" | Tee-Object -FilePath $logPath -Append
"[STEP1] Execution time: $([string]$elapsed)" | Tee-Object -FilePath $logPath -Append
"[STEP1] Output file size (bytes): $outSize" | Tee-Object -FilePath $logPath -Append

# Validate success criteria: file exists and has >=1 match line
if (!(Test-Path $outPath)) {
  'MISSING evidence file' | Tee-Object -FilePath $logPath -Append
  exit 2
}

$inv = Get-Content -Path $outPath -TotalCount 5000
$matchLines = $inv | Where-Object { $_ -match '\|\s*BACKEND/planbuddy_v9' -or $_ -match '\| .*planbuddy_v9' }
# More reliable: count rows with category separators
$rows = $inv | Where-Object { $_ -like '| * | * | * | * |' }

if ($totalMatches -lt 1 -or $rows.Count -lt 2) {
  "[STEP1] ERROR: No matches found; refusing to proceed." | Tee-Object -FilePath $logPath -Append
  exit 3
}

# Completion print (for capturing in terminal)
"Production files scanned: $productionCount" 
"Files containing matches: $filesWithMatches" 
"Total matches: $totalMatches" 
"Execution time: $([string]$elapsed)" 
"Evidence file location: $outPath" 

# also print first 20 inventory entries
"First 20 inventory entries:" 
$firstEntries = Get-Content -Path $outPath | Select-Object -Skip 6 -First 20
$firstEntries | ForEach-Object { $_ }

exit 0


